# baseURL 변경
# baseURL = "/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

# title 변경
title = "AWS Unity Android Build Pipeline"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
#ignoreFiles = [ "\\.*lab3\\.*" ]

# description, author 변경
[params]
  description = "AWS Unity Android Build Pipeline"
  author = "Seongwan Koo"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-facebook-square'></i> Facebook"
  url = "https://www.facebook.com/groups/awskrug/"
  weight = 1030

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/studydev/hugo-workshop"
  weight = 1040

[Languages.ko]
title = "AWS Unity Android Build Pipeline"
weight = 1
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 크레딧"
url = "/credits/"
weight = 30
