title = "AWS Unity Android Build Pipeline"
googleAnalytics = "UA-189406980-1"
anguageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
#baseURL = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Seongwan Koo"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-facebook-square'></i> Facebook"
  url = "https://www.facebook.com/groups/awskrug/"
  weight = 1030

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/seongwank/aws-unity-build-sample"
  weight = 1040

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

#  [Languages.en]
#    weight = 2
#    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://hugo.awsdemo.kr?region=ap-northeast-2"
